<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'example\\carrier' => '/Carrier.php',
                'example\\container' => '/Container.php',
                'example\\containerid' => '/ContainerId.php',
                'example\\exception' => '/exceptions/Exception.php',
                'example\\invalidcapacityexception' => '/exceptions/InvalidCapacityException.php',
                'example\\invalidcontaineridexception' => '/exceptions/InvalidContainerIdException.php',
                'example\\invalidnameexception' => '/exceptions/InvalidNameException.php',
                'example\\invalidnumberofportsexception' => '/exceptions/InvalidNumberOfPortsException.php',
                'example\\invalidnumberofshipsexception' => '/exceptions/InvalidNumberOfShipsException.php',
                'example\\invalidportexception' => '/exceptions/InvalidPortException.php',
                'example\\invalidpositionexception' => '/exceptions/InvalidPositionException.php',
                'example\\port' => '/Port.php',
                'example\\ship' => '/Ship.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
